### ISSUE TITLE
knob behavior for volume 

### ISSUE THREAD

**Issue by Julisons** [BeppiMenozzi/Knob#4]
is not good

**Comment by Julisons** [comment]
it should act as a slider , simple

**Comment by BeppiMenozzi** [comment]
What would you change?

**Comment by Julisons** [comment]
I think it should behave like a circular seek bar ...a slide in a way . This link contains a nice circular seekbar....how it moves and behave is what am trying to air out here.

https://github.com/devadvance/circularseekbar

**Comment by BeppiMenozzi** [comment]
You mean that it's not understanding circular gestures, alas work with arcs and degrees?
I think that different applications would need both linear and circular gesture management, it's in my list of todo things to add the circular behaviour in future. Please note that in certain cases circular would not be good: if you put the knob in a corner, for example, values near the edges could not be reached with an arc behaviour.

**Comment by BeppiMenozzi** [comment]
Done.
