### ISSUE TITLE
The volume knob circular swipe is odd, sometime i swipe left,it toggle to the right.It feels physical inconsistency

### ISSUE THREAD

**Issue by asalin** [BeppiMenozzi/Knob#6]

**Comment by BeppiMenozzi** [comment]
Can you create an exact case that can be reproduced please?

**Comment by CarlyAmar** [comment]
This might be because the knob is not set to the swipe setting you think it is. I think default is Left/Right, not circular. Be sure to set it using the constants. @asalin

**Comment by Thomas-Vos** [comment]
This is a bug, the default value (circular) is always overridden by the xml attributes. @asalin, quick fix is to manually set the swipe direction to circular in your xml file. @BeppiMenozzi, see pull request #7 for a fix.
